"""initial schema

Revision ID: 7b1d62fc1b15
Revises: 
Create Date: 2026-09-22 15:49:46.839462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b1d62fc1b15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner', 'name', name='uq_repos_owner_name')
    )
    op.create_table('issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'number', name='uq_issues_repo_number')
    )
    op.create_index('ix_issues_comments_count', 'issues', ['comments_count'], unique=False)
    op.create_index('ix_issues_repo_id', 'issues', ['repo_id'], unique=False)
    op.create_index('ix_issues_repo_state', 'issues', ['repo_id', 'state'], unique=False)
    op.create_index('ix_issues_updated_at', 'issues', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_issues_updated_at', table_name='issues')
    op.drop_index('ix_issues_repo_state', table_name='issues')
    op.drop_index('ix_issues_repo_id', table_name='issues')
    op.drop_index('ix_issues_comments_count', table_name='issues')
    op.drop_table('issues')
    op.drop_table('repos')
    # ### end Alembic commands ###
